package CoreJava.Utils;

public class OracleQueries {
	
	public final static String GETSTUDENTBYGMAIL = "SELECT * FROM STUDENT "
			+ "WHERE EMAIL = ?";
	
	public final static String GETALLINSTRUCTORS = "SELECT * FROM INSTRUCTOR";
	public final static String GETINSTRUCTORBYGMAIL = "SELECT * FROM INSTRUCTOR "
			+ "WHERE EMAIL = ?";
	
	public final static String GETALLCOURSES = "SELECT * FROM COURSE";
	public final static String GETCOURSEBYINSTRUCTOR = "SELECT COURSE.COURSE_ID, COURSE.COURSE_NAME, COURSE.MINIMUN_GPA FROM COURSE "
			+ "INNER JOIN TEACHING ON COURSE.COURSE_ID = TEACHING.COURSE_ID "
			+ "WHERE TEACHING.INSTRUCTOR_ID = ?";
	
	public final static String SAVESTUDENTTOCOURSE = "INSERT INTO ATTENDING "
			+ "(COURSE_ID, STUDENT_ID) "
			+ "VALUES (?,?)";
	
	public final static String GETCOURSEBYSTUDENT = "SELECT COURSE.COURSE_NAME, INSTRUCTOR.FULL_NAME, INSTRUCTOR.EMAIL FROM ATTENDING "
			+ "INNER JOIN COURSE ON ATTENDING.COURSE_ID = COURSE.COURSE_ID "
			+ "INNER JOIN TEACHING ON ATTENDING.COURSE_ID = TEACHING.COURSE_ID "
			+ "INNER JOIN INSTRUCTOR ON TEACHING.INSTRUCTOR_ID = INSTRUCTOR.INSTRUCTOR_ID "
			+ "WHERE ATTENDING.STUDENT_ID = ?";
	
	public final static String SAVEINSTRUCTORTOCOURSE = "INSERT INTO TEACHING "
			+ "(COURSE_ID, INSTRUCTOR_ID) "
			+ "VALUES (?,?)";
	
	public final static String GETINSTRUCTORSCOURSES = "SELECT COURSE.COURSE_NAME, COURSE.MINIMUN_GPA, INSTRUCTOR.FULL_NAME, INSTRUCTOR.EMAIL FROM TEACHING "
			+ "INNER JOIN COURSE ON TEACHING.COURSE_ID = COURSE.COURSE_ID "
			+ "INNER JOIN INSTRUCTOR ON TEACHING.INSTRUCTOR_ID = INSTRUCTOR.INSTRUCTOR_ID";
}
